# Generated by Django 3.2.3 on 2023-10-22 12:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название бренда', max_length=255, verbose_name='Бренд')),
                ('description', models.TextField(help_text='Укажите описание', max_length=500, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Бренд',
                'verbose_name_plural': 'Бренды',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Мета-название страницы')),
                ('meta_description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Мета-описание страницы')),
                ('name', models.CharField(help_text='Введите название категории', max_length=255, verbose_name='Название')),
                ('description', models.CharField(blank=True, help_text='Введите описание категории', max_length=255, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='Изображение')),
                ('slug', models.SlugField(unique=True, verbose_name='Слаг')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='CountryProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название страны', max_length=255, verbose_name='Название страны')),
            ],
            options={
                'verbose_name': ('Страна',),
                'verbose_name_plural': 'Страны',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, help_text='Укажите итоговую стоимость', max_digits=6, verbose_name='Итоговая стоимость')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата заказа')),
                ('address', models.TextField(help_text='Введите адрес доставки', max_length=500, verbose_name='Адрес доставки')),
                ('is_payed', models.BooleanField(default=False, help_text='Укажите статус оплаты', verbose_name='Статус оплаты')),
                ('customer', models.ForeignKey(help_text='Выберите пользователя(Покупатель)', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Покупатель')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Мета-название страницы')),
                ('meta_description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Мета-описание страницы')),
                ('name', models.CharField(help_text='Введите название товара', max_length=255, verbose_name='Наименование')),
                ('price', models.DecimalField(decimal_places=2, default=1, help_text='Укажите стоимость товара', max_digits=10, verbose_name='Стоимость')),
                ('image', models.ImageField(blank=True, help_text='Добавить изображние для поста', null=True, upload_to='products/', verbose_name='Изображение')),
                ('description', models.TextField(blank=True, help_text='Введите описание товара', max_length=500, verbose_name='Описание')),
                ('slug', models.SlugField(unique=True, verbose_name='Слаг')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.brand', verbose_name='Бренд')),
                ('category', models.ForeignKey(help_text='Выберите категорию', on_delete=django.db.models.deletion.CASCADE, to='products.category', verbose_name='Категория')),
                ('country', models.ForeignKey(help_text='Выберите страну производства', on_delete=django.db.models.deletion.CASCADE, to='products.countryproduct', verbose_name='Страна')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='Shop_basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.OneToOneField(help_text='Укажите пользователя(Покупатель)', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Покупатель')),
            ],
            options={
                'verbose_name': 'Корзина с товарами',
                'verbose_name_plural': 'Корзины с товарами',
            },
        ),
        migrations.CreateModel(
            name='Shop_basket_items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Укажите количество', verbose_name='Количество')),
                ('product', models.ForeignKey(help_text='Выберите товар', on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Товар')),
                ('shop_basket', models.ForeignKey(help_text='Выберите корзину', on_delete=django.db.models.deletion.CASCADE, to='products.shop_basket', verbose_name='Корзина')),
            ],
            options={
                'verbose_name': 'Товар для корзины',
                'verbose_name_plural': 'Товары для корзин',
            },
        ),
        migrations.AddField(
            model_name='shop_basket',
            name='products',
            field=models.ManyToManyField(help_text='Выберите товар', through='products.Shop_basket_items', to='products.Product', verbose_name='Товары'),
        ),
        migrations.CreateModel(
            name='ProductQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.PositiveIntegerField(help_text='Укажите количество товара на складе', verbose_name='Доступно на складе')),
                ('product', models.ForeignKey(help_text='Выберите товар', on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Количество доступного товара',
                'verbose_name_plural': 'Количество доступных товаров',
            },
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Укажите количество', verbose_name='Количество')),
                ('order', models.ForeignKey(help_text='Выберите заказ', on_delete=django.db.models.deletion.CASCADE, to='products.order', verbose_name='Заказ')),
                ('product', models.ForeignKey(help_text='Выберите товар', on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Товары для заказа',
                'verbose_name_plural': 'Товары для заказов',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(help_text='Выберите товар', through='products.OrderItems', to='products.Product', verbose_name='Товары'),
        ),
    ]
