# Generated by Django 3.2.3 on 2024-03-02 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название бренда', max_length=255, verbose_name='Бренд')),
                ('description', models.TextField(help_text='Укажите описание', max_length=500, verbose_name='Описание')),
                ('slug', models.SlugField(help_text='URL для бренда', unique=True, verbose_name='Слаг')),
            ],
            options={
                'verbose_name': 'Бренд',
                'verbose_name_plural': 'Бренды',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, help_text='Мета-название для SEO', max_length=255, null=True, verbose_name='Мета-название страницы')),
                ('meta_description', models.CharField(blank=True, help_text='Мета-описание для SEO', max_length=255, null=True, verbose_name='Мета-описание страницы')),
                ('name', models.CharField(help_text='Введите название категории', max_length=255, verbose_name='Название')),
                ('description', models.CharField(blank=True, help_text='Введите описание категории', max_length=255, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, help_text='Добавить изображение', null=True, upload_to='categories/', verbose_name='Изображение')),
                ('slug', models.SlugField(help_text='URL для категории', unique=True, verbose_name='Слаг')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='CountryProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название страны', max_length=255, verbose_name='Название страны')),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, help_text='Мета-название для SEO', max_length=255, null=True, verbose_name='Мета-название страницы')),
                ('meta_description', models.CharField(blank=True, help_text='Мета-описание для SEO', max_length=255, null=True, verbose_name='Мета-описание страницы')),
                ('name', models.CharField(help_text='Введите название товара', max_length=255, unique=True, verbose_name='Наименование')),
                ('price', models.DecimalField(decimal_places=2, default=1, help_text='Укажите стоимость товара', max_digits=10, verbose_name='Стоимость')),
                ('quantity', models.PositiveIntegerField(default=0, help_text='Укажите количество товара на складе', verbose_name='Количество товара')),
                ('image', models.ImageField(blank=True, help_text='Добавить изображние для поста', null=True, upload_to='products/', verbose_name='Изображение')),
                ('description', models.TextField(blank=True, help_text='Введите описание товара', max_length=500, verbose_name='Описание')),
                ('slug', models.SlugField(help_text='URL для товара', unique=True, verbose_name='Слаг')),
                ('brand', models.ForeignKey(help_text='Выберите бренд', on_delete=django.db.models.deletion.CASCADE, to='products.brand', verbose_name='Бренд')),
                ('category', models.ForeignKey(help_text='Выберите категорию', on_delete=django.db.models.deletion.CASCADE, to='products.category', verbose_name='Категория')),
                ('country', models.ForeignKey(help_text='Выберите страну производства', on_delete=django.db.models.deletion.CASCADE, to='products.countryproduct', verbose_name='Страна')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
