# Generated by Django 3.2.3 on 2023-10-08 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='categories',
            name='meta_description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Мета-описание страницы'),
        ),
        migrations.AddField(
            model_name='categories',
            name='meta_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Мета-название страницы'),
        ),
        migrations.AddField(
            model_name='products',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='products',
            name='meta_description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Мета-описание страницы'),
        ),
        migrations.AddField(
            model_name='products',
            name='meta_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Мета-название страницы'),
        ),
    ]
