# Generated by Django 3.2.3 on 2023-10-29 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='countryproduct',
            options={'verbose_name': 'Страна', 'verbose_name_plural': 'Страны'},
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(default=0, help_text='Укажите количество товара на складе', verbose_name='Количество товара'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, help_text='Добавить изображение', null=True, upload_to='categories/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='category',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Мета-описание для SEO', max_length=255, null=True, verbose_name='Мета-описание страницы'),
        ),
        migrations.AlterField(
            model_name='category',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Мета-название для SEO', max_length=255, null=True, verbose_name='Мета-название страницы'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(help_text='URL для категории', unique=True, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(help_text='Выберите бренд', on_delete=django.db.models.deletion.CASCADE, to='products.brand', verbose_name='Бренд'),
        ),
        migrations.AlterField(
            model_name='product',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Мета-описание для SEO', max_length=255, null=True, verbose_name='Мета-описание страницы'),
        ),
        migrations.AlterField(
            model_name='product',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Мета-название для SEO', max_length=255, null=True, verbose_name='Мета-название страницы'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(help_text='URL для товара', unique=True, verbose_name='Слаг'),
        ),
        migrations.DeleteModel(
            name='ProductQuantity',
        ),
    ]
