# Generated by Django 3.2.3 on 2024-03-03 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='vendor_code',
            field=models.PositiveIntegerField(default=1, help_text='Введите код товара', verbose_name='Код товара'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('name', 'vendor_code'), name='unique_name_vendor_code'),
        ),
    ]
