# Generated by Django 3.2.3 on 2023-10-29 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20231029_0741'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='slug',
            field=models.SlugField(default='apple', help_text='URL для бренда', unique=True, verbose_name='Слаг'),
            preserve_default=False,
        ),
    ]
