# Generated by Django 3.2.3 on 2023-11-12 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_shop_basket_items_unique_product_shop_basket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop_basket_items',
            name='product',
            field=models.ForeignKey(help_text='Выберите товар', on_delete=django.db.models.deletion.CASCADE, related_name='shopbasketproduct', to='products.product', verbose_name='Товар'),
        ),
    ]
