# Generated by Django 3.2.3 on 2023-11-12 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20231112_0626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop_basket',
            name='products',
            field=models.ManyToManyField(help_text='Выберите товар', through='products.Shop_basket_items', to='products.Product', verbose_name='Товары'),
        ),
    ]
