# Generated by Django 3.2.3 on 2023-11-25 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_shop_basket_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(help_text='Введите название товара', max_length=255, unique=True, verbose_name='Наименование'),
        ),
    ]
