# Generated by Django 3.2.3 on 2023-11-25 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_product_name'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='orderitems',
            constraint=models.UniqueConstraint(fields=('product', 'order'), name='unique_product_order'),
        ),
    ]
