# Generated by Django 3.2.3 on 2023-11-28 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_orderitems_unique_product_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Укажите итоговую стоимость', max_digits=10, verbose_name='Итоговая стоимость'),
        ),
    ]
