# Generated by Django 3.2.3 on 2024-03-09 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_auto_20240309_1529'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderpaymenet',
            old_name='idempotentence_key',
            new_name='idempotence_key',
        ),
    ]
