# Generated by Django 3.2.3 on 2024-03-09 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_order_status'),
        ('payment', '0004_alter_orderpaymenet_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderPaymenet',
            new_name='OrderPayment',
        ),
    ]
