# Generated by Django 3.2.3 on 2024-03-09 19:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_auto_20240309_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderpayment',
            name='idempotence_key',
            field=models.UUIDField(default=uuid.UUID('b2d5e5ec-5f03-4c51-87f8-0b2995bd59d1'), editable=False, help_text='Ключ идемпотентности', primary_key=True, serialize=False, verbose_name='Ключ идемпотентности'),
        ),
        migrations.AlterField(
            model_name='orderpayment',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, help_text='Сумма платежа', max_digits=15, verbose_name='Сумма'),
        ),
    ]
