# Generated by Django 3.2.3 on 2024-03-09 19:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0009_auto_20240309_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderpayment',
            name='idempotence_key',
            field=models.UUIDField(default=uuid.UUID('061f9941-1c6c-4120-9c2c-23991a924e02'), editable=False, help_text='Ключ идемпотентности', primary_key=True, serialize=False, verbose_name='Ключ идемпотентности'),
        ),
        migrations.AlterField(
            model_name='orderpayment',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=3, editable=False, help_text='Сумма платежа', max_digits=15, verbose_name='Сумма'),
        ),
    ]
