# Generated by Django 3.2.3 on 2024-03-09 19:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0010_auto_20240309_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderpayment',
            name='idempotence_key',
            field=models.UUIDField(default=uuid.UUID('9f5df403-6052-47c3-bbfc-861bae3e93ef'), editable=False, help_text='Ключ идемпотентности', primary_key=True, serialize=False, verbose_name='Ключ идемпотентности'),
        ),
        migrations.AlterField(
            model_name='orderpayment',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, help_text='Сумма платежа', max_digits=10, verbose_name='Сумма'),
        ),
    ]
