# Generated by Django 3.2.3 on 2024-03-08 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, help_text='Укажите итоговую стоимость', max_digits=10, verbose_name='Итоговая стоимость')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата заказа')),
                ('phone', models.PositiveIntegerField(help_text='Телефон, формат: 79687773366', verbose_name='Номер телефона')),
                ('email', models.EmailField(help_text='Укажите Email', max_length=254, verbose_name='Email')),
                ('comments', models.TextField(help_text='Введите комментарий', max_length=500, verbose_name='Комментарий')),
                ('address', models.TextField(help_text='Введите адрес доставки', max_length=500, verbose_name='Адрес доставки')),
                ('status', models.CharField(choices=[('AC', 'Активный'), ('CA', 'Отмененный')], max_length=300, verbose_name='Статус Заказа')),
                ('is_payed', models.BooleanField(default=False, help_text='Укажите статус оплаты', verbose_name='Статус оплаты')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Укажите количество', verbose_name='Количество')),
                ('order', models.ForeignKey(help_text='Выберите заказ', on_delete=django.db.models.deletion.CASCADE, to='orders.order', verbose_name='Заказ')),
                ('product', models.ForeignKey(help_text='Выберите товар', on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Товары для заказа',
                'verbose_name_plural': 'Товары для заказов',
            },
        ),
        migrations.CreateModel(
            name='OrderRefund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата создания', verbose_name='Дата создания')),
                ('comment', models.TextField(blank=True, help_text='текст для комментария', null=True, verbose_name='Комментарий')),
                ('order', models.ForeignKey(help_text='id Заказа', on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='orders.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Возврат',
                'verbose_name_plural': 'Возвраты',
            },
        ),
        migrations.CreateModel(
            name='OrderItemsRefund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveBigIntegerField(help_text='Количество', verbose_name='Количество')),
                ('order_item', models.ForeignKey(help_text='id товара в Заказе', on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='orders.orderitems', verbose_name='Возвращаемый товар')),
                ('refund', models.ForeignKey(help_text='id возвращаемого Заказа', on_delete=django.db.models.deletion.CASCADE, related_name='orderitemsrefunds', to='orders.orderrefund', verbose_name='Возврат')),
            ],
            options={
                'verbose_name': 'Возвращаемый товар',
                'verbose_name_plural': 'Возвращаемые товары',
            },
        ),
    ]
