# Generated by Django 3.2.3 on 2024-03-02 21:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(help_text='Выберите пользователя(Покупатель)', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Покупатель'),
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(help_text='Выберите товар', through='orders.OrderItems', to='products.Product', verbose_name='Товары'),
        ),
        migrations.AddConstraint(
            model_name='orderitems',
            constraint=models.UniqueConstraint(fields=('product', 'order'), name='unique_product_order'),
        ),
    ]
