# Generated by Django 3.2.3 on 2024-03-09 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_rename_comments_order_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('AC', 'Активный'), ('EN', 'Завершенный'), ('CA', 'Отмененный')], default=('AC', 'Активный'), max_length=300, verbose_name='Статус Заказа'),
        ),
    ]
