# Generated by Django 3.2.3 on 2024-03-09 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(help_text='Телефон, формат: 79687773366', max_length=14, verbose_name='Номер телефона'),
        ),
    ]
