# Generated by Django 3.2.3 on 2024-05-11 16:25

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0026_alter_orderitemsrefund_order_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitemsrefund',
            name='order_item',
            field=models.ForeignKey(help_text='id товара в Заказе', limit_choices_to={'order': django.db.models.expressions.F('refunds__order')}, on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='orders.orderitems', verbose_name='Возвращаемый товар'),
        ),
    ]
