# Generated by Django 3.2.3 on 2024-06-09 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0031_alter_orderitemsrefund_order_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderrefund',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Активный'), ('FINISHED', 'Завершенный'), ('CANCELLED', 'Отмененный')], default='ACTIVE', max_length=300, verbose_name='Статус Заказа'),
        ),
    ]
