# Generated by Django 3.2.3 on 2024-02-05 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_comments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['-pub_date'], 'verbose_name': ('Комментарий',), 'verbose_name_plural': 'Комментарии'},
        ),
    ]
