# Generated by Django 3.2.3 on 2024-02-10 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20240210_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Опубликован'),
        ),
    ]
