# Generated by Django 3.2.3 on 2024-03-01 20:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop_basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.OneToOneField(help_text='Укажите пользователя(Покупатель)', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Покупатель')),
            ],
            options={
                'verbose_name': 'Корзина с товарами',
                'verbose_name_plural': 'Корзины с товарами',
            },
        ),
        migrations.CreateModel(
            name='Shop_basket_items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Укажите количество', verbose_name='Количество')),
                ('product', models.ForeignKey(help_text='Выберите товар', on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Товар')),
                ('shop_basket', models.ForeignKey(help_text='Выберите корзину', on_delete=django.db.models.deletion.CASCADE, to='shop_basket.shop_basket', verbose_name='Корзина')),
            ],
            options={
                'verbose_name': 'Товар для корзины',
                'verbose_name_plural': 'Товары для корзин',
            },
        ),
        migrations.AddField(
            model_name='shop_basket',
            name='products',
            field=models.ManyToManyField(help_text='Выберите товар', through='shop_basket.Shop_basket_items', to='products.Product', verbose_name='Товары'),
        ),
        migrations.AddConstraint(
            model_name='shop_basket_items',
            constraint=models.UniqueConstraint(fields=('product', 'shop_basket'), name='unique_product_shop_basket'),
        ),
    ]
