# Generated by Django 3.2.3 on 2024-03-02 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop_basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Корзина с товарами',
                'verbose_name_plural': 'Корзины с товарами',
            },
        ),
        migrations.CreateModel(
            name='Shop_basket_items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Укажите количество', verbose_name='Количество')),
                ('product', models.ForeignKey(help_text='Выберите товар', on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Товар')),
                ('shop_basket', models.ForeignKey(help_text='Выберите корзину', on_delete=django.db.models.deletion.CASCADE, to='shop_basket.shop_basket', verbose_name='Корзина')),
            ],
            options={
                'verbose_name': 'Товар для корзины',
                'verbose_name_plural': 'Товары для корзин',
            },
        ),
    ]
