# Generated by Django 3.2.3 on 2024-03-08 16:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop_basket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop_basket',
            name='customer',
            field=models.OneToOneField(help_text='Укажите пользователя(Покупатель)', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Покупатель'),
        ),
        migrations.AddField(
            model_name='shop_basket',
            name='products',
            field=models.ManyToManyField(help_text='Выберите товар', through='shop_basket.Shop_basket_items', to='products.Product', verbose_name='Товары'),
        ),
        migrations.AddConstraint(
            model_name='shop_basket_items',
            constraint=models.UniqueConstraint(fields=('product', 'shop_basket'), name='unique_product_shop_basket'),
        ),
    ]
